[phases.setup]
nixPkgs = ["ffmpeg", "python311"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt", "python assets/generate_assets.py"]

[start]
cmd = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
